vpn_subnet_id: 37

ipv6_prefix: "{{ yikai_net.north_prefix }}"

# the default dns server (ipv6) in hetzner cloud does not work from outside, so unreachable after setting up yikai-net's ipv6 address
dns_server: 8.8.4.4

tunnelbroker:
  # https://www.tunnelbroker.ch/tunnel/18379
  # Zurich
  # Its german endpoint is broken
  tb-ch:
    remote: 193.33.94.248
    subnet: 2a09:4c0:1e0:523::/64

  # https://my.bgptunnel.com/bgp_sessions
  tb-ifog:
    remote: 193.148.248.18
    # my addr: 2a0c:9a40:a001::72
    # peer addr: 2a0c:9a40:a001::71
    subnet: 2a0c:9a40:a001::70/126
    mode: gre
    mtu: 1448
    routes:
      - 2000::/3

  tb-north:
    remote: 2a0c:9a40:2510:1001::10e4  # north-bgp.blahgeek.com
    local: 2a01:4f8:c012:95c9::1
    subnet: "{{ yikai_net.north_prefix | ansible.utils.ipsubnet(64, 1) }}"
    mode: gre6
    extra_up_cmds:
      - /bin/ip -6 route add 2a0c:9a40:2510:1001::10e4/128 via fe80::1 dev eth0 || true

bgp:
  tb_ch:
    peer_asn: 58057
    peer_addr: 2a09:4c0:1e0:523::1
    prefixes:
      - "{{ ipv6_prefix }}"
      - "{{ yikai_net.home_prefix }}"
    export_filter: |
      bgp_path.prepend({{ my_asn }});
      bgp_path.prepend({{ my_asn }});
      accept;

  tb_ifog:
    peer_asn: 209533
    peer_addr: 2a0c:9a40:a001::71
    prefixes:
      - "{{ ipv6_prefix }}"
      - "{{ yikai_net.home_prefix }}"
    export_filter: |
      accept;
